-- 0006_expand_trade_logs.sql
-- Milestone E: trade_logs full lifecycle fields (OPEN/CLOSED), stop-loss consistency, AI metadata.

-- PostgreSQL: ALTER TABLE ADD COLUMN不支持AFTER，需要按顺序添加
ALTER TABLE trade_logs
  ADD COLUMN IF NOT EXISTS status VARCHAR(16) NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS actor VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS leverage INT NULL,
  ADD COLUMN IF NOT EXISTS stop_dist_pct DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS stop_price DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS client_order_id VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS exchange_order_id VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS robot_score DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS ai_prob DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS open_reason_code VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS open_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS close_reason_code VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS close_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS entry_time_ms BIGINT NULL,
  ADD COLUMN IF NOT EXISTS exit_time_ms BIGINT NULL;

CREATE INDEX IF NOT EXISTS idx_trade_logs_symbol_status_time ON trade_logs(symbol, status, created_at);

-- PostgreSQL: 使用触发器实现ON UPDATE CURRENT_TIMESTAMP
CREATE TRIGGER update_trade_logs_updated_at BEFORE UPDATE ON trade_logs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE trade_logs_history
  ADD COLUMN IF NOT EXISTS status VARCHAR(16) NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS actor VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS leverage INT NULL,
  ADD COLUMN IF NOT EXISTS stop_dist_pct DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS stop_price DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS client_order_id VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS exchange_order_id VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS robot_score DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS ai_prob DECIMAL(28, 12) NULL,
  ADD COLUMN IF NOT EXISTS open_reason_code VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS open_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS close_reason_code VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS close_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS entry_time_ms BIGINT NULL,
  ADD COLUMN IF NOT EXISTS exit_time_ms BIGINT NULL;
